const $=id=>document.getElementById(id);let sessionId="default",lastAnswer="",currentFile=null;
async function api(path,opts={}){const r=await fetch(path,opts);let data;try{data=await r.json()}catch{data={detail:await r.text()}}if(!r.ok)throw new Error(data.detail||data.error||`HTTP ${r.status}`);return data}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2800)}
function esc(s){return String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function renderMessages(items){const box=$("messages");box.innerHTML="";for(const m of items){const el=document.createElement("div");el.className="message "+m.role;el.innerHTML=`<div class="msg-avatar">${m.role==="user"?"YOU":"P"}</div><div class="bubble">${esc(m.content)}</div>`;box.append(el)}box.scrollTop=box.scrollHeight}
function addMessage(role,content){const box=$("messages");const welcome=box.querySelector(".welcome");if(welcome)welcome.remove();const el=document.createElement("div");el.className="message "+role;el.innerHTML=`<div class="msg-avatar">${role==="user"?"YOU":"P"}</div><div class="bubble">${esc(content)}</div>`;box.append(el);box.scrollTop=box.scrollHeight}
async function refreshSessions(){try{const d=await api("/sessions");$("sessions").innerHTML=d.items.map(s=>`<div class="session ${s.id===sessionId?"selected":""}" data-session="${esc(s.id)}"><span>${esc(s.title||s.id)}</span>${s.id!=="default"?`<button data-delete-session="${esc(s.id)}" title="Delete session">×</button>`:""}</div>`).join("");}catch(e){toast(e.message)}}
async function openSession(id){sessionId=id;const d=await api("/sessions");const s=d.items.find(x=>x.id===id);$("page-title").textContent=s?.title||"Chat";const res=await api("/chat/history?session_id="+encodeURIComponent(id)).catch(()=>null);if(res)renderMessages(res.items);else{if(id==="default")renderMessages([]);else renderMessages([])}refreshSessions()}
function setView(name){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id==="view-"+name));document.querySelectorAll(".navitem").forEach(v=>v.classList.toggle("active",v.dataset.view===name));$("page-title").textContent=({chat:"Chat",memory:"Memory",tools:"Tools & plugins",files:"Files & vision",settings:"Settings & dashboard"})[name]||name;if(name==="memory")loadMemories();if(name==="settings")loadDashboard();if(name==="tools")loadPlugins()}
document.querySelectorAll(".navitem").forEach(b=>b.onclick=()=>setView(b.dataset.view));
$("new-chat").onclick=async()=>{sessionId="chat-"+crypto.randomUUID();await refreshSessions();renderMessages([]);setView("chat");$("page-title").textContent="New chat";$("prompt").focus()};
$("sessions").onclick=async e=>{const del=e.target.closest("[data-delete-session]");if(del){e.stopPropagation();if(confirm("Delete this session and its messages?")){await api("/sessions/"+encodeURIComponent(del.dataset.deleteSession),{method:"DELETE"});if(sessionId===del.dataset.deleteSession){sessionId="default";renderMessages([])}refreshSessions()}return}const row=e.target.closest("[data-session]");if(row){sessionId=row.dataset.session;document.querySelectorAll(".session").forEach(x=>x.classList.toggle("selected",x===row));$("page-title").textContent=row.querySelector("span").textContent;const hist=await api("/chat/history?session_id="+encodeURIComponent(sessionId));renderMessages(hist.items);}});
$("chat-form").onsubmit=async e=>{e.preventDefault();const text=$("prompt").value.trim();if(!text)return;addMessage("user",text);$("prompt").value="";$("prompt").style.height="auto";const btn=$("chat-form").querySelector(".send");btn.disabled=true;const placeholder=document.createElement("div");placeholder.className="message assistant";placeholder.innerHTML='<div class="msg-avatar">P</div><div class="bubble">PIXEL is thinking…</div>';$("messages").append(placeholder);try{const r=await fetch("/chat/stream",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,session_id:sessionId,temperature:.7,use_tools:$("use-tools").checked})});if(!r.ok){const er=await r.json();throw new Error(er.detail||"Chat failed")}const reader=r.body.getReader(),decoder=new TextDecoder();let buffer="",answer="";const bubble=placeholder.querySelector(".bubble");bubble.textContent="";while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split("\n\n");buffer=chunks.pop();for(const chunk of chunks){const line=chunk.split("\n").find(x=>x.startsWith("data: "));if(!line)continue;const data=JSON.parse(line.slice(6));if(data.token){answer+=data.token;bubble.textContent=answer;$("messages").scrollTop=$("messages").scrollHeight}if(data.error)throw new Error(data.error)}}lastAnswer=answer;await refreshSessions()}catch(err){placeholder.querySelector(".bubble").textContent="Error: "+err.message;toast(err.message)}finally{btn.disabled=false;$("prompt").focus()}};
$("prompt").oninput=e=>{e.target.style.height="auto";e.target.style.height=Math.min(e.target.scrollHeight,180)+"px"};
document.querySelectorAll("[data-prompt]").forEach(b=>b.onclick=()=>{$("prompt").value=b.dataset.prompt;$("prompt").focus()});
$("chat-file").onchange=e=>{currentFile=e.target.files[0];if(currentFile){$("file-label").textContent=currentFile.name;setView("files");$("document-file").files=e.target.files;toast("File selected. Use Read file in Files & vision.")}};
async function loadMemories(q=""){const url=q?"/memory/search?q="+encodeURIComponent(q):"/memory";try{const d=await api(url);$("memory-list").innerHTML=d.items.length?d.items.map(m=>`<div class="data-item"><div><p>${esc(m.text)}</p><small>#${m.id} · ${esc(m.category)} · importance ${m.importance} · used ${m.use_count||0} times</small></div><div class="data-actions"><button data-edit-memory="${m.id}">Edit</button><button data-delete-memory="${m.id}">Delete</button></div></div>`).join(""):'<div class="empty">No memories found.</div>'}catch(e){toast(e.message)}}
$("search-memory").onclick=()=>loadMemories($("memory-search").value.trim());$("memory-search").onkeydown=e=>{if(e.key==="Enter")loadMemories(e.target.value.trim())};
$("memory-list").onclick=async e=>{const del=e.target.closest("[data-delete-memory]"),edit=e.target.closest("[data-edit-memory]");if(del){if(confirm("Delete this memory?")){await api("/memory/"+del.dataset.deleteMemory,{method:"DELETE"});loadMemories()}}if(edit){const id=edit.dataset.editMemory;const old=await api("/memory");const item=old.items.find(x=>x.id==id);if(!item)return;const text=prompt("Edit memory text:",item.text);if(text===null)return;const category=prompt("Category:",item.category)||item.category;const importance=Number(prompt("Importance 1–5:",item.importance)||item.importance);await api("/memory/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,category,importance})});loadMemories();toast("Memory updated")}};
$("add-memory").onclick=async()=>{const text=prompt("What should PIXEL remember?");if(!text?.trim())return;const category=prompt("Category:","general")||"general";const importance=Number(prompt("Importance 1–5:","3")||3);await api("/learn",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,category,importance,source:"user"})});loadMemories();toast("Memory saved")};
$("calc-run").onclick=async()=>{try{const d=await api("/tools/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:"calculator",arguments:{expression:$("calc-expression").value}})});$("calc-result").textContent=JSON.stringify(d,null,2)}catch(e){$("calc-result").textContent=e.message}};
$("web-run").onclick=async()=>{try{const d=await api("/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:$("web-query").value,max_results:5})});$("web-result").innerHTML=d.results.map(r=>`<div class="web-result"><a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.title)}</a><p>${esc(r.snippet)}</p></div>`).join("")||"No results."}catch(e){$("web-result").textContent=e.message}};
async function loadPlugins(){try{const d=await api("/plugins");$("plugin-list").innerHTML=d.items.map(p=>`<div class="data-item"><div><b>${esc(p.name)}</b><small>${esc(p.description||p.error||"Local plugin")}</small></div></div>`).join("")||'<div class="empty">No plugins discovered. Add a trusted .py plugin with a top-level `plugin` object.</div>'}catch(e){toast(e.message)}}$("refresh-plugins").onclick=loadPlugins;
$("read-document").onclick=async()=>{const f=$("document-file").files[0];if(!f){toast("Choose a file first.");return}const fd=new FormData();fd.append("file",f);fd.append("remember",$("remember-document").checked?"true":"false");$("document-result").textContent="Reading…";try{const d=await api("/files/read",{method:"POST",body:fd});$("document-result").textContent=d.text+(d.truncated?"\n\n[Preview truncated]":"");toast(`Read ${d.characters} characters`)}catch(e){$("document-result").textContent=e.message}};
$("analyze-image").onclick=async()=>{const f=$("vision-file").files[0];if(!f){toast("Choose an image first.");return}const fd=new FormData();fd.append("file",f);fd.append("prompt",$("vision-prompt").value||"Describe this image.");$("vision-result").textContent="Analyzing…";try{const d=await api("/vision",{method:"POST",body:fd});$("vision-result").textContent=d.answer}catch(e){$("vision-result").textContent=e.message}};
async function loadDashboard(){try{const [d,h,s]=await Promise.all([api("/dashboard"),api("/health"),api("/api/settings")]);$("dashboard-cards").innerHTML=[["Memories",d.memory_count],["Sessions",d.sessions],["Tools",d.tools],["Model",h.model.loaded?"Loaded":"Lazy / not loaded"]].map(([a,b])=>`<div class="stat"><span>${a}</span><strong>${esc(b)}</strong></div>`).join("");$("version").textContent="v"+s.version}catch(e){toast(e.message)}}$("refresh-settings").onclick=loadDashboard;
$("theme-toggle").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("pixel-theme",document.body.classList.contains("light")?"light":"dark")};if(localStorage.getItem("pixel-theme")==="light")document.body.classList.add("light");
$("voice").onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast("Voice input is not supported by this browser.");return}const r=new SR();r.lang=navigator.language||"en-US";r.onresult=e=>$("prompt").value=e.results[0][0].transcript;r.onerror=()=>toast("Voice input failed.");r.start()};
$("speak-last").onclick=()=>{if(!lastAnswer){toast("No answer to speak yet.");return}if(!("speechSynthesis"in window)){toast("Speech output is not supported.");return}speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(lastAnswer))};
refreshSessions();loadDashboard();